name: Semantic Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  semantic-pr-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Run Semantic Pull Request action
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v4
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
