name: CI/CD for Staging Environment

on:
  pull_request:
    branches:
      - master  # Khi có pull request merge vào nhánh main

jobs:
  staging-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:ci  # Chạy các kiểm thử phù hợp với staging

    - name: Build application
      run: npm run build

    - name: Deploy to Staging Server
      run: |
        scp -r ./dist user@staging-server:/path/to/project
        ssh user@staging-server 'pm2 restart app'
